### ISSUE TITLE
Mac Deploy Issue (windows is fine)

### ISSUE THREAD

**Issue by mdg215199** [normj/netcore-simple-websockets-chat-app#1]
This might be an easy fix, as I've not had any issue deploying on Windows.  On Mac, it goes through and appears to push all lambda's, zip in s3, etc.   At the end, it tries to create the apigateway w/ socket and then after sitting on this for several seconds, it ends up causing the error.  I tried to look through most other issues in google, and tried most examples on it (even though their issue wasn't accurate with what the error appeared to be happening).   

Anyways, total details while deploying:
MacBook-Pro:netcore-simple-websockets-chat-app matgar$ sudo dotnet lambda deploy-serverless aspnetcoreWebsocketsApiGatewayExample --region us-east-2 --s3-bucket sos-test-east-2
Password:
Amazon Lambda Tools for .NET Core applications (3.1.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Processing CloudFormation resource OnConnectFunction
Initiate packaging of OnConnect/ for resource OnConnectFunction
Executing publish command
... invoking 'dotnet publish', working folder '/Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/bin/Release/netcoreapp2.1/publish'
... Disabling compilation context to reduce package size. If compilation context is needed pass in the "/p:PreserveCompilationContext=false" switch.
... publish: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restoring packages for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/OnConnect.csproj...
... publish:   Restoring packages for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/CommonChat.csproj...
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/obj/CommonChat.csproj.nuget.g.props.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/obj/CommonChat.csproj.nuget.g.targets.
... publish:   Restore completed in 178.79 ms for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/CommonChat.csproj.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/obj/OnConnect.csproj.nuget.g.props.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/obj/OnConnect.csproj.nuget.g.targets.
... publish:   Restore completed in 745.37 ms for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/OnConnect.csproj.
... publish:   CommonChat -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/bin/Release/netstandard2.0/CommonChat.dll
... publish:   OnConnect -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/bin/Release/netcoreapp2.1/rhel.7.2-x64/OnConnect.dll
... publish:   OnConnect -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/bin/Release/netcoreapp2.1/publish/
Changed permissions on published dll (chmod +r AWSSDK.DynamoDBv2.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.APIGatewayEvents.dll).
Changed permissions on published dll (chmod +r OnConnect.dll).
Changed permissions on published dll (chmod +r AWSSDK.Core.dll).
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Core.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Serialization.Json.dll).
Changed permissions on published dll (chmod +r CommonChat.dll).
Zipping publish folder /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnConnect/bin/Release/netcoreapp2.1/publish to /tmp/OnConnectFunction-CodeUri-636821498828592160.zip
... zipping:   adding: AWSSDK.DynamoDBv2.dll (deflated 66%)
... zipping:   adding: Amazon.Lambda.APIGatewayEvents.dll (deflated 61%)
... zipping:   adding: OnConnect.deps.json (deflated 83%)
... zipping:   adding: OnConnect.dll (deflated 55%)
... zipping:   adding: AWSSDK.Core.dll (deflated 67%)
... zipping:   adding: OnConnect.pdb (deflated 29%)
... zipping:   adding: Newtonsoft.Json.dll (deflated 60%)
... zipping:   adding: CommonChat.pdb (deflated 26%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 57%)
... zipping:   adding: Amazon.Lambda.Serialization.Json.dll (deflated 56%)
... zipping:   adding: OnConnect.runtimeconfig.json (deflated 23%)
... zipping:   adding: CommonChat.dll (deflated 62%)
Created publish archive (/tmp/OnConnectFunction-CodeUri-636821498828592160.zip).
Lambda project successfully packaged: /tmp/OnConnectFunction-CodeUri-636821498828592160.zip
Uploading to S3. (Bucket: sos-test-east-2 Key: OnConnectFunction-CodeUri-636821498828592160-636821498889078140.zip)
... Progress: 17%
... Progress: 34%
... Progress: 51%
... Progress: 68%
... Progress: 86%
... Progress: 100%
Processing CloudFormation resource OnDisconnectFunction
Initiate packaging of OnDisconnect/ for resource OnDisconnectFunction
Executing publish command
... invoking 'dotnet publish', working folder '/Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/bin/Release/netcoreapp2.1/publish'
... Disabling compilation context to reduce package size. If compilation context is needed pass in the "/p:PreserveCompilationContext=false" switch.
... publish: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restoring packages for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/OnDisconnect.csproj...
... publish:   Restore completed in 26.99 ms for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/CommonChat.csproj.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/obj/OnDisconnect.csproj.nuget.g.props.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/obj/OnDisconnect.csproj.nuget.g.targets.
... publish:   Restore completed in 421.49 ms for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/OnDisconnect.csproj.
... publish:   CommonChat -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/bin/Release/netstandard2.0/CommonChat.dll
... publish:   OnDisconnect -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/bin/Release/netcoreapp2.1/rhel.7.2-x64/OnDisconnect.dll
... publish:   OnDisconnect -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/bin/Release/netcoreapp2.1/publish/
Changed permissions on published dll (chmod +r AWSSDK.DynamoDBv2.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.APIGatewayEvents.dll).
Changed permissions on published dll (chmod +r OnDisconnect.dll).
Changed permissions on published dll (chmod +r AWSSDK.Core.dll).
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Core.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Serialization.Json.dll).
Changed permissions on published dll (chmod +r CommonChat.dll).
Zipping publish folder /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/OnDisconnect/bin/Release/netcoreapp2.1/publish to /tmp/OnDisconnectFunction-CodeUri-636821498916544200.zip
... zipping:   adding: AWSSDK.DynamoDBv2.dll (deflated 66%)
... zipping:   adding: Amazon.Lambda.APIGatewayEvents.dll (deflated 61%)
... zipping:   adding: OnDisconnect.runtimeconfig.json (deflated 23%)
... zipping:   adding: OnDisconnect.dll (deflated 54%)
... zipping:   adding: OnDisconnect.deps.json (deflated 83%)
... zipping:   adding: AWSSDK.Core.dll (deflated 67%)
... zipping:   adding: OnDisconnect.pdb (deflated 29%)
... zipping:   adding: Newtonsoft.Json.dll (deflated 60%)
... zipping:   adding: CommonChat.pdb (deflated 26%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 57%)
... zipping:   adding: Amazon.Lambda.Serialization.Json.dll (deflated 56%)
... zipping:   adding: CommonChat.dll (deflated 62%)
Created publish archive (/tmp/OnDisconnectFunction-CodeUri-636821498916544200.zip).
Lambda project successfully packaged: /tmp/OnDisconnectFunction-CodeUri-636821498916544200.zip
Uploading to S3. (Bucket: sos-test-east-2 Key: OnDisconnectFunction-CodeUri-636821498916544200-636821498956379050.zip)
... Progress: 17%
... Progress: 34%
... Progress: 51%
... Progress: 68%
... Progress: 86%
... Progress: 100%
Processing CloudFormation resource SendMessageFunction
Initiate packaging of SendMessage/ for resource SendMessageFunction
Executing publish command
... invoking 'dotnet publish', working folder '/Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/bin/Release/netcoreapp2.1/publish'
... Disabling compilation context to reduce package size. If compilation context is needed pass in the "/p:PreserveCompilationContext=false" switch.
... publish: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restoring packages for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/SendMessage.csproj...
... publish:   Restore completed in 23.86 ms for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/CommonChat.csproj.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/obj/SendMessage.csproj.nuget.g.props.
... publish:   Generating MSBuild file /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/obj/SendMessage.csproj.nuget.g.targets.
... publish:   Restore completed in 409.99 ms for /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/SendMessage.csproj.
... publish:   CommonChat -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/CommonChat/bin/Release/netstandard2.0/CommonChat.dll
... publish:   SendMessage -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/bin/Release/netcoreapp2.1/rhel.7.2-x64/SendMessage.dll
... publish:   SendMessage -> /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/bin/Release/netcoreapp2.1/publish/
Changed permissions on published dll (chmod +r AWSSDK.DynamoDBv2.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.APIGatewayEvents.dll).
Changed permissions on published dll (chmod +r SendMessage.dll).
Changed permissions on published dll (chmod +r AWSSDK.Core.dll).
Changed permissions on published dll (chmod +r AWSSDK.ApiGatewayManagementApi.dll).
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Core.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Serialization.Json.dll).
Changed permissions on published dll (chmod +r CommonChat.dll).
Zipping publish folder /Users/matgar/Documents/projects/netcore-simple-websockets-chat-app/SendMessage/bin/Release/netcoreapp2.1/publish to /tmp/SendMessageFunction-CodeUri-636821498977992020.zip
... zipping:   adding: AWSSDK.DynamoDBv2.dll (deflated 66%)
... zipping:   adding: Amazon.Lambda.APIGatewayEvents.dll (deflated 61%)
... zipping:   adding: SendMessage.dll (deflated 52%)
... zipping:   adding: AWSSDK.Core.dll (deflated 67%)
... zipping:   adding: SendMessage.pdb (deflated 34%)
... zipping:   adding: AWSSDK.ApiGatewayManagementApi.dll (deflated 58%)
... zipping:   adding: Newtonsoft.Json.dll (deflated 60%)
... zipping:   adding: CommonChat.pdb (deflated 26%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 57%)
... zipping:   adding: SendMessage.deps.json (deflated 83%)
... zipping:   adding: Amazon.Lambda.Serialization.Json.dll (deflated 56%)
... zipping:   adding: SendMessage.runtimeconfig.json (deflated 23%)
... zipping:   adding: CommonChat.dll (deflated 62%)
Created publish archive (/tmp/SendMessageFunction-CodeUri-636821498977992020.zip).
Lambda project successfully packaged: /tmp/SendMessageFunction-CodeUri-636821498977992020.zip
Uploading to S3. (Bucket: sos-test-east-2 Key: SendMessageFunction-CodeUri-636821498977992020-636821499018961710.zip)
... Progress: 16%
... Progress: 33%
... Progress: 50%
... Progress: 67%
... Progress: 84%
... Progress: 100%
Uploading to S3. (Bucket: sos-test-east-2 Key: aspnetcoreWebsocketsApiGatewayExample-template-636821499051006770.yaml)
... Progress: 100%
Unknown error executing command: Device not configured
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.GetExistingStackAsync(String stackName) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\Commands\DeployServerlessCommand.cs:line 558
   at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.PerformActionAsync() in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\Commands\DeployServerlessCommand.cs:line 176
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44
MacBook-Pro:netcore-simple-websockets-chat-app matgar$ 

By chance, would you know that is causing this (and also, what I could potentially use to have this running)?  Thanks in advance!

**Comment by mdg215199** [comment]
Disregard this comment, seems to be how I have things set up on my router.
